#!/bin/bash

github_id='llamallama'
user='chris'
extra_drive='/dev/sdb'

run_updates() {
  apt-get update && apt-get -y dist-upgrade
}

install_ssh() {
  apt-get -y install ssh-import-id

  su "$user" -c "ssh-import-id-gh $github_id"
}

install_common_utils() {
  apt-get -y install nfs-common
}

install_docker() {
  if [[ -z "${1-}" ]]
  then
    echo "No docker version specified"
    exit 1
  fi

  apt-get -y install \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg-agent \
      software-properties-common

  curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
  add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/debian \
     $(lsb_release -cs) \
     stable"
  apt-get update
  apt-get -y install "docker-ce=$docker_version" "docker-ce-cli=$docker_version" containerd.io

  usermod -a -G docker "$user"
}

setup_network() {
  local ip_address=$(hostname -I | cut -d' ' -f1)
  local ip_octal=$(echo "$ip_address" | awk -F '.' '{ print $4 }')
  local hostname=$(host "$ip_address" | awk '{ print $5 }' | awk -F '.' '{ print $1 }')
  local storage_ip="192.168.200.$ip_octal"

  cat <<- EOF >> /etc/network/interfaces
	auto ens19
	iface ens19 inet static
		address $storage_ip
		netmask 255.255.255.0
	EOF

  # Reverts to iptables legacy
  update-alternatives --set iptables /usr/sbin/iptables-legacy

  # Set hostname
  sed -i "s/debianbase/$hostname/g" /etc/{hostname,hosts}
  hostname "$hostname"
}

add_drive() {
  # Mount extra drive if available
  if [[ -b "$extra_drive" ]]
  then
    mkfs.ext4 "$extra_drive"
    cat <<-EOF >> /etc/systemd/system/mnt-localstore.mount
		[Unit]
		Description=External k8s mount

		[Mount]
		What=$extra_drive
		Where=/mnt/localstore
		Type=ext4
		Options=defaults

		[Install]
		WantedBy=multi-user.target
		EOF

    systemctl daemon-reload
    systemctl enable mnt-localstore.mount
  fi
}

remove_autologin() {
  # Remove autologin
  rm -rf '/etc/systemd/system/getty@.service.d'
  sed -i '$d' ~/.bashrc
}
