#!/bin/bash

set -euf -o pipefail

echo "Sleeping 5 seconds while network initializes"
sleep 5

source functions

docker_version='5:18.09.9~3-0~debian-buster'

run_updates
install_ssh
install_common_utils
setup_network
add_drive

if [[ "$(hostname)" == *"rancher"* ]]
then
  install_docker "$docker_version"
fi
