#!/bin/bash

set -euf -o pipefail

source functions

docker_version='5:18.09.9~3-0~debian-buster'

run_updates
install_ssh
install_docker "$docker_version"
setup_network
add_drive

if [[ "$(hostname)" == *"rancher"* ]]
then
  setup_docker
fi
